[[context]]
line = 136
content = """
            )

        fixes = []
        for advice in diag.get("advices", {}).get("advices", []):
            diff = advice.get("diff")
            if diff:
                edits = _create_edits_from_diff(line_index, diff, file_path)
"""

[[result]]
line = 139
rule_id = "misspelling"
message = "advices ==> advice"
