[[block]]
line = 1
context = """
1ABC=2345
asFD=123
FOO=BAR
FOO=BAZ
"""

[[block.result]]
line = 1
column = 0
rule_id = "LeadingCharacter"
message = "Invalid leading character detected"

[[block.result]]
line = 2
column = 0
rule_id = "LowercaseKey"
message = "The asFD key should be in uppercase"

[[block.result]]
line = 3
column = 0
rule_id = "UnorderedKey"
message = "The FOO key should go before the asFD key"

[[block.result]]
line = 4
column = 0
rule_id = "DuplicatedKey"
message = "The FOO key is duplicated"

[[block.result]]
line = 4
column = 0
rule_id = "UnorderedKey"
message = "The FOO key should go before the FOO key"
