[[context]]
line = 1
content = """
1ABC=2345
asFD=123
FOO=BAR
FOO=BAZ
"""

[[context.result]]
line = 1
rule_id = "LeadingCharacter"
message = "Invalid leading character detected"

[[context.result]]
line = 2
rule_id = "LowercaseKey"
message = "The asFD key should be in uppercase"

[[context.result]]
line = 3
rule_id = "UnorderedKey"
message = "The FOO key should go before the asFD key"

[[context.result]]
line = 4
rule_id = "DuplicatedKey"
message = "The FOO key is duplicated"

[[context.result]]
line = 4
rule_id = "UnorderedKey"
message = "The FOO key should go before the FOO key"
