[[block]]
line = 1
context = """
 i = 2
"""

[[block.result]]
line = 1
column = 1
rule_id = "SC2148"
message = "Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive."

[[block.result]]
line = 1
column = 4
rule_id = "SC2283"
message = "Remove spaces around = to assign (or use [ ] to compare, or quote '=' if literal)."
