[[block]]
line = 0

[[block.result]]
column = 0
rule_id = "failed"
message = """
Error: config compilation contains errors: config compilation contains errors:
\t- Cannot find circleci/node@2.99 in the orb registry. Check that the namespace, orb name and version are correct.
"""
