[[context]]
line = 1
content = """
# bad.md

# This file has reallly long lines

Line is OK- Make a realy long line that breaks the layout rules completely. Make a realy long line
that breaks
But this should be ignored because of config

"""

[[result]]
line = 3
rule_id = "misspelling"
message = "reallly ==> really"

[[result]]
line = 5
rule_id = "misspelling"
message = "realy ==> really, relay"
