[[block]]
line = 3
context = '''
banned_strings_check(
    name = "check",
    description = "Found do not land",
    strings = ["DONOTLAND", "DO-NOT-LAND", "DO_NOT_LAND", "donotland", "do-not-land", "do_not_land"],
)
'''

[[block.result]]
line = 6
column = 17
rule_id = "found"
message = "Found do not land: `DONOTLAND'"

[[block.result]]
line = 6
column = 30
rule_id = "found"
message = "Found do not land: `DO-NOT-LAND'"

[[block.result]]
line = 6
column = 45
rule_id = "found"
message = "Found do not land: `DO_NOT_LAND'"

[[block.result]]
line = 6
column = 60
rule_id = "found"
message = "Found do not land: `donotland'"

[[block.result]]
line = 6
column = 73
rule_id = "found"
message = "Found do not land: `do-not-land'"

[[block.result]]
line = 6
column = 88
rule_id = "found"
message = "Found do not land: `do_not_land'"
