[[block]]
line = 3
context = '''
banned_strings_check(
    name = "check",
    description = "Found curly quote",
    strings = ["“", "”", "„", "‟", "‘", "’"],
)
'''

[[block.result]]
line = 6
column = 17
rule_id = "found"
message = "Found curly quote: `“'"

[[block.result]]
line = 6
column = 22
rule_id = "found"
message = "Found curly quote: `”'"

[[block.result]]
line = 6
column = 27
rule_id = "found"
message = "Found curly quote: `„'"

[[block.result]]
line = 6
column = 32
rule_id = "found"
message = "Found curly quote: `‟'"

[[block.result]]
line = 6
column = 37
rule_id = "found"
message = "Found curly quote: `‘'"

[[block.result]]
line = 6
column = 42
rule_id = "found"
message = "Found curly quote: `’'"
