[[context]]
line = 3
content = '''
banned_strings_check(
    name = "check",
    description = "Found curly quote",
    strings = ["“", "”", "„", "‟", "‘", "’"],
)
'''

[[context.result]]
line = 6
column = 17
rule_id = "found"
message = "Found curly quote: `“'"

[[context.result]]
line = 6
column = 22
rule_id = "found"
message = "Found curly quote: `”'"

[[context.result]]
line = 6
column = 27
rule_id = "found"
message = "Found curly quote: `„'"

[[context.result]]
line = 6
column = 32
rule_id = "found"
message = "Found curly quote: `‟'"

[[context.result]]
line = 6
column = 37
rule_id = "found"
message = "Found curly quote: `‘'"

[[context.result]]
line = 6
column = 42
rule_id = "found"
message = "Found curly quote: `’'"
