[[context]]
line = 1
content = """
FROM ubuntu:22.04

RUN true
RUN true
"""

[[context.result]]
line = 4
column = 1
rule_id = "DL3059"
message = "Multiple consecutive `RUN` instructions. Consider consolidation."
