[[context]]
line = 1
content = '''
Hello
aws_token = "AKIALALEMEL33243OLIA"
World
'''

[[context.result]]
line = 2
column = 15
rule_id = "aws-access-token"
message = "Identified a pattern that may indicate AWS credentials, risking unauthorized cloud resource access and data breaches on AWS platforms."
