[[context]]
line = 1
content = '''
import dill
import StringIO

# dill
pick = dill.dumps({"a": "b", "c": "d"})
print(dill.loads(pick))

file_obj = StringIO.StringIO()
dill.dump([1, 2, "3"], file_obj)
'''

[[context.result]]
line = 1
column = 1
rule_id = "B403"
message = "Consider possible security implications associated with dill module."

[[context.result]]
line = 6
column = 7
rule_id = "B301"
message = "Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue."
