[[context]]
line = 5
content = """
        pass


import sys


class NoDocstring(object):
"""

[[context.result]]
line = 8
column = 1
rule_id = "F401"
message = "'sys' imported but unused"

[[context.result]]
line = 8
column = 1
rule_id = "E402"
message = "module level import not at top of file"
