[[context]]
line = 1
content = """
FROM ubuntu:22.04

RUN true
RUN true
"""

[[result]]
line = 1
rule_id = "CKV_DOCKER_2"
message = "Ensure that HEALTHCHECK instructions have been added to container images"

[[result]]
line = 1
rule_id = "CKV_DOCKER_3"
message = "Ensure that a user for the container has been created"
