[[context]]
line = 1
content = """
[Good link](#test-header)
[Good link](https://www.google.com)
[Bad link](#bad-header)
[Bad link](https://nowhere.com/bad-link)


"""

[[result]]
line = 3
column = 1
rule_id = "MD051/link-fragments"
message = 'Link fragments should be valid [Context: "[Bad link](#bad-header)"]'
