[[context]]
line = 2
content = '''
    pass


foo("wrong")
'''

[[result]]
line = 5
column = 5
rule_id = "reportArgumentType"
message = '''
Argument of type "Literal['wrong']" cannot be assigned to parameter "bar" of type "int" in function "foo"
  "Literal['wrong']" is not assignable to "int"'''
