[[block]]
line = 8
context = '''
	platform="linux"
fi

output=$(my current platform is $platform)
echo $output
'''

[[block.result]]
line = 11
column = 33
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 12
column = 6
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."
