[[block]]
line = 4
context = '''



output2=$(my current platform is $platform2)

output=$(my current platform is $platform)


if [ "$(uname)" == "Darwin" ]; then
'''

[[block.result]]
line = 7
column = 34
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 7
column = 34
rule_id = "SC2154"
message = "platform2 is referenced but not assigned (did you mean 'platform'?)."

[[block.result]]
line = 9
column = 33
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block]]
line = 15
context = '''
	platform="linux"
fi

output=$(my current platform is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
output2=$(my current platform2 is $platform)
'''

[[block.result]]
line = 18
column = 1
rule_id = "SC2034"
message = "output appears unused. Verify use (or export if used externally)."

[[block.result]]
line = 18
column = 33
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 19
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 20
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 21
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 22
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 23
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 24
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 25
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 26
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 27
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 28
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 29
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 30
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 31
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 32
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 33
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 34
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 35
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 36
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 37
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 38
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 39
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 40
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 41
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 42
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 43
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 44
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 45
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 46
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 47
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 48
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 49
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 50
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 51
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 52
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 53
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 54
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 55
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 56
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 57
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 58
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 59
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 60
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 61
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 62
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 63
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 64
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 65
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 66
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 67
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 68
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 69
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 70
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 71
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 72
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 73
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 74
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 75
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 76
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 77
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 78
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 79
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 80
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 81
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 82
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 83
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 84
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 85
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 86
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 87
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."

[[block.result]]
line = 88
column = 1
rule_id = "SC2034"
message = "output2 appears unused. Verify use (or export if used externally)."

[[block.result]]
line = 88
column = 35
rule_id = "SC2086"
message = "Double quote to prevent globbing and word splitting."
