[[context]]

[[context.result]]
rule_id = "dead-link"
message = "Dead link found: #bad-header (status code: 404)"

[[context.result]]
rule_id = "dead-link"
message = "Dead link found: https://nowhere.com/bad-link (status code: 0)"
