[[block]]
line = 1
context = """
# bad.md

# This file has reallly long lines

Line is OK- Make a realy long line that breaks the layout rules completely. Make a realy long line
that breaks
But this should be ignored because of config

"""

[[block.result]]
line = 3
column = 17
rule_id = "misspelling"
message = "Unknown word (reallly) Suggestions: [really, rally, realty, reilly, regally]"

[[block.result]]
line = 5
column = 20
rule_id = "misspelling"
message = "Unknown word (realy) Suggestions: [really*, relay, real, rely, ready]"

[[block.result]]
line = 5
column = 84
rule_id = "misspelling"
message = "Unknown word (realy) Suggestions: [really*, relay, real, rely, ready]"
