[[context]]
line = 1088
content = """
    "node_modules/require-from-string": {
      "version": "2.0.2",
      "resolved": "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz",
      "integrity": "sha512-Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==",
      "peer": true,
      "engines": {
        "node": ">=0.10.0"
"""

[[result]]
line = 1091
rule_id = "misspelling"
message = "vEw ==> view, vow, vex"
