[[context]]
line = 6
content = """
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
"""

[[result]]
line = 9
rule_id = "CKV_CIRCLECIPIPELINES_2"
message = "Ensure the pipeline image version is referenced via hash not arbitrary tag."
