[[context]]
line = 6
content = """
    Type: String
    Default: 0
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: test.io
"""

[[result]]
line = 9
rule_id = "CKV2_AWS_71"
message = "Ensure AWS ACM Certificate domain name does not include wildcards"
