[[context]]
line = 1
content = """
on:
  schedule:
    # Cron syntax is not correct
    - cron: '0 */3 * *'
    # Interval of scheduled job is too small (job runs too frequently)
    - cron: '* */3 * * *'

"""

[[context.result]]
line = 4
column = 13
rule_id = "quoted-strings"
message = "string value is redundantly quoted with any quotes"
