[[block]]
line = 1
context = """
“Hello world”
"""

[[block.result]]
line = 1
column = 1
rule_id = "found"
message = "Found curly quote: `“'"

[[block.result]]
line = 1
column = 13
rule_id = "found"
message = "Found curly quote: `”'"
