[[context]]
line = 1
content = """
“Hello world”
"""

[[result]]
line = 1
column = 1
rule_id = "found"
message = "Found curly quote: `“'"

[[result]]
line = 1
column = 13
rule_id = "found"
message = "Found curly quote: `”'"
