[[context]]
line = 1
content = '''
aws_access_key_id = "AKIAIO5FODNN7EXAMPLE"

aws_token = "AKIALALEMEL33243OLIA"

private_key = """-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
'''

[[result]]
line = 1
rule_id = "CKV_SECRET_2"
message = "AWS Access Key"

[[result]]
line = 1
rule_id = "CKV_SECRET_13"
message = "Private Key"

[[result]]
line = 3
rule_id = "CKV_SECRET_2"
message = "AWS Access Key"
