[[block]]
line = 1
context = '''
aws_access_key_id = "AKIAIO5FODNN7EXAMPLE"

aws_token = "AKIALALEMEL33243OLIA"

private_key = """-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
'''

[[block.result]]
line = 1
column = 0
rule_id = "CKV_SECRET_2"
message = "AWS Access Key"

[[block.result]]
line = 1
column = 0
rule_id = "CKV_SECRET_13"
message = "Private Key"

[[block.result]]
line = 3
column = 0
rule_id = "CKV_SECRET_2"
message = "AWS Access Key"
