[[context]]
line = 1
content = '''
 variable "ssl_certificates" {
  type = "map"
  default = {
      lorem-elb-us-west-3 = "lorem"
        ipsum-elb-us-east-1 = "ipsum"
'''

[[result]]
line = 2
column = 10
rule_id = "error"
message = "Invalid quoted type constraints"
