[[local_workspace]]
name = "prelude"
path = "."

[options.prelude.runtime]
node.version = "22.12.0"
python.version = "3.13.0"
go.version = "1.23.4"

[options.prelude.tool]
actionlint.check = true
actionlint.version = "1.7.7"
buildifier.fmt = true
buildifier.version = "7.3.1"
biome.check = true
biome.version = "1.9.4"
clippy.check = true
flake8.check = true
flake8.version = "7.1.1"
git_diff.check = true
gitleaks.check = true
gitleaks.version = "8.23.2"
hadolint.check = true
hadolint.version = "2.12.1-beta"
ruff.check = true
ruff.fmt = true
ruff.version = "0.9.2"
prettier.fmt = true
prettier.version = "3.4.2"
prisma.fmt = true
prisma.version = "6.3.0"
pyright.check = true
pyright.version = "1.1.390"
rustfmt.fmt = true
shellcheck.check = true
shellcheck.version = "0.10.0"
shfmt.version = "3.4.2"
shfmt.fmt = true
taplo.fmt = true
taplo.version = "0.9.3"
yamllint.check = true
yamllint.version = "1.35.1"
do_not_land.check = true
no_curly_quotes.check = true
# Linter that just sleeps and produces no output. Useful for testing the progress bar.
# sleep.check = true
#openai-document.check = true

#[options.prelude.rules]
#openai.api_key = "<api_key>"

[[ignore]]
globs = ["tool/do_not_land/**", ".tk/config.toml"]
checks = ["prelude//tool/do_not_land:check"]

[[ignore]]
globs = ["tool/no_curly_quotes/**"]
checks = ["prelude//tool/no_curly_quotes:check"]

[[ignore]]
globs = [".tk/baseline/**"]
