[[local_workspace]]
name = "prelude"
path = "."

[options.prelude.runtime]
node.version = "22.12.0"
python.version = "3.12.8"
go.version = "1.23.4"

[options.prelude.tool]
actionlint.check = true
actionlint.version = "1.7.7"
autopep8.fmt = true
autopep8.version = "2.3.2"
bandit.check = true
bandit.version = "1.8.2"
biome.check = true
biome.version = "1.9.4"
black.fmt = true
black.version = "24.10.0"
buf.check = true
buf.fmt = true
buf.version = "1.50.0"
buildifier.fmt = true
buildifier.version = "7.3.1"
cfn-lint.check = true
cfn-lint.version = "1.23.0"
cmake_format.fmt = true
cmake_format.version = "0.6.13"
codespell.check = true
codespell.version = "2.4.1"
cspell.check = true
cspell.version = "8.17.3"
clippy.check = true
checkov.check = true
checkov.secrets = true
checkov.version = "3.2.358"
circleci.check = true
circleci.version = "0.1.31425"
cue_format.fmt = true
cue_format.version = "0.12.0"
do_not_land.check = true
flake8.check = true
flake8.version = "7.1.1"
git_diff.check = true
gitleaks.check = true
gitleaks.version = "8.23.2"
gofmt.fmt = true
hadolint.check = true
hadolint.version = "2.12.1-beta"
no_curly_quotes.check = true
osv-scanner.check = true
osv-scanner.version = "1.9.2"
prettier.fmt = true
prettier.version = "3.4.2"
prisma.fmt = true
prisma.version = "6.3.0"
pyright.check = true
pyright.version = "1.1.390"
ruff.check = true
ruff.fmt = true
ruff.version = "0.9.2"
rustfmt.fmt = true
shellcheck.check = true
shellcheck.version = "0.10.0"
shfmt.fmt = true
shfmt.version = "3.4.2"
taplo.fmt = true
taplo.version = "0.9.3"
yamllint.check = true
yamllint.version = "1.35.1"
yapf.fmt = true
yapf.version = "0.43.0"
# Linter that just sleeps and produces no output. Useful for testing the progress bar.
# sleep.check = true
#openai-document.check = true

#[options.prelude.rules]
#openai.api_key = "<api_key>"

[[ignore]]
globs = [".tk/baseline/**"]

# Too many false positives
[[ignore]]
globs = ["**", "!tool/cspell/test_data/**"]
checks = ["prelude//tool/cspell:check"]
