[[context]]
line = 1
content = """
on:
  schedule:
    # Cron syntax is not correct
    - cron: '0 */3 * *'
"""

[[context.result]]
line = 1
rule_id = "CKV2_GHA_1"
message = "Ensure top-level permissions are not set to write-all"
