[[context]]
line = 1
content = '''
import dill
import StringIO

# dill
pick = dill.dumps({"a": "b", "c": "d"})
'''

[[result]]
line = 2
column = 8
rule_id = "reportMissingImports"
message = 'Import "StringIO" could not be resolved'
