[[context]]
line = 3
content = """
{% block body %}{% endblock %}
<link rel="stylesheet" href="/static/css/nav.scss" type="text/x-scss" charset="utf-8"/>
<script type="text/javascript" src="/static/lib/markdown-it/markdown-it.js"></script>
<img src="/static/images/hi.jpg" alt="Hi!">
"""

[[result]]
line = 6
rule_id = "H006"
message = "Img tag should have height and width attributes."
