[[block]]
line = 1
context = '''

#whitespace below vvv

  #A malindented comment
if __name__ == "__main__" :
      a=4+1
      b=( 2*7 )
      c = [1,
           2,
           3
      ]
      print(a/b)
'''

[[block.result]]
line = 2
column = 1
rule_id = "E265"
message = "block comment should start with '# '"

[[block.result]]
line = 4
column = 3
rule_id = "E265"
message = "block comment should start with '# '"

[[block.result]]
line = 4
column = 3
rule_id = "E114"
message = "indentation is not a multiple of 4 (comment)"

[[block.result]]
line = 4
column = 3
rule_id = "E116"
message = "unexpected indentation (comment)"

[[block.result]]
line = 5
column = 26
rule_id = "E203"
message = "whitespace before ':'"

[[block.result]]
line = 6
column = 7
rule_id = "E111"
message = "indentation is not a multiple of 4"

[[block.result]]
line = 6
column = 7
rule_id = "E117"
message = "over-indented"

[[block.result]]
line = 6
column = 8
rule_id = "E225"
message = "missing whitespace around operator"

[[block.result]]
line = 7
column = 7
rule_id = "E111"
message = "indentation is not a multiple of 4"

[[block.result]]
line = 7
column = 8
rule_id = "E225"
message = "missing whitespace around operator"

[[block.result]]
line = 7
column = 10
rule_id = "E201"
message = "whitespace after '('"

[[block.result]]
line = 7
column = 14
rule_id = "E202"
message = "whitespace before ')'"

[[block.result]]
line = 8
column = 7
rule_id = "E111"
message = "indentation is not a multiple of 4"

[[block.result]]
line = 11
column = 7
rule_id = "E124"
message = "closing bracket does not match visual indentation"

[[block.result]]
line = 12
column = 7
rule_id = "E111"
message = "indentation is not a multiple of 4"
