[[context]]
line = 1
content = 'basic_auth = "https://admin:admin@the-internet.herokuapp.com/basic_auth"'

[[result]]
line = 1
rule_id = "URI"
message = "Secret detected: https://admin:********@the-internet.herokuapp.com/basic_auth"
