[[block]]
line = 1
context = 'basic_auth = "https://admin:admin@the-internet.herokuapp.com/basic_auth"'

[[block.result]]
line = 1
column = 0
rule_id = "URI"
message = "Secret detected: https://admin:********@the-internet.herokuapp.com/basic_auth"
