[[context]]
line = 1
content = """
object: {True: 1, 1: True}
foo: 'bar'
stuff:
  - key 2: v
    key 1: val
"""

[[context.result]]
line = 2
column = 6
rule_id = "quoted-strings"
message = "string value is redundantly quoted with any quotes"
