[[context]]
line = 1
content = """
const foobar = () => { }
const barfoo = () => { }

enum Bar { Baz };

const foo = (bar: Bar) => {
  switch (bar) {
"""

[[context]]
line = 10
content = """
      barfoo();
      break;
  }
  { !foo ? null : 1 }
}
"""

[[result]]
line = 4
column = 6
rule_id = "lint/style/useEnumInitializers"
message = "This enum declaration contains members that are implicitly initialized."

[[result]]
line = 13
column = 3
rule_id = "lint/complexity/noUselessLoneBlockStatements"
message = "This block statement doesn't serve any purpose and can be safely removed."
