[[context]]
line = 1
content = """
Hello world!
Hallo, wurld?
"""

[[context.result]]
line = 2
column = 1
rule_id = "Spelling"
message = "Did you really mean 'Hallo'?"

[[context.result]]
line = 2
column = 8
rule_id = "Spelling"
message = "Did you really mean 'wurld'?"
