[[block]]
line = 1
context = """
Hello world!
Hallo, wurld?
"""

[[block.result]]
line = 2
column = 1
rule_id = "Spelling"
message = "Did you really mean 'Hallo'?"

[[block.result]]
line = 2
column = 8
rule_id = "Spelling"
message = "Did you really mean 'wurld'?"
