[[block]]
line = 1
context = '''
aws_access_key_id = "AKIAIO5FODNN7EXAMPLE"

aws_token = "AKIALALEMEL33243OLIA"

private_key = """-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
'''

[[block.result]]
line = 3
column = 13
rule_id = "B105"
message = "Possible hardcoded password: 'AKIALALEMEL33243OLIA'"
