name: Rusty Check
on:
  pull_request: {}
  push:
    branches: [main]

permissions: read-all

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2
      - run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - uses: actions/setup-node@v4
      - run: npm install --prefix tool/stylelint/test_data
      - run: tk check -a
      # Print the server log
      - run: cat $(tk paths | jq -r .server_stderr_file)
