[[context]]
line = 1
content = '''

syntax = "proto3";

package trunk;

enum GoodEnum {
  lower_case_UNSPECIFIED = 0;
  GOOD_ENUM_VALUE_1 = 1;
}
'''

[[result]]
line = 1
column = 1
rule_id = "FILE_LOWER_SNAKE_CASE"
message = 'Filename "buf.in.proto" should be lower_snake_case.proto, such as "buf_in.proto".'

[[result]]
line = 4
column = 1
rule_id = "PACKAGE_DIRECTORY_MATCH"
message = 'Files with package "trunk" must be within a directory "trunk" relative to root but were in directory "tool/buf/test_data".'

[[result]]
line = 4
column = 1
rule_id = "PACKAGE_VERSION_SUFFIX"
message = 'Package name "trunk" should be suffixed with a correctly formed version, such as "trunk.v1".'

[[result]]
line = 7
column = 3
rule_id = "ENUM_VALUE_UPPER_SNAKE_CASE"
message = 'Enum value name "lower_case_UNSPECIFIED" should be UPPER_SNAKE_CASE, such as "LOWER_CASE_UNSPECIFIED".'

[[result]]
line = 7
column = 3
rule_id = "ENUM_VALUE_PREFIX"
message = 'Enum value name "lower_case_UNSPECIFIED" should be prefixed with "GOOD_ENUM_".'
