[[block]]
line = 5
context = """
        pass


import sys


class NoDocstring(object):
"""

[[block.result]]
line = 8
column = 1
rule_id = "E402"
message = "Module level import not at top of file"

[[block.result]]
line = 8
column = 8
rule_id = "F401"
message = "`sys` imported but unused"
